[package]
name = "trie-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "get"
harness = false

[[bench]]
name = "has"
harness = false

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "stress"
harness = false
